### ISSUE TITLE
Run hello_world.py TypeError: ActorBuilder.add_box_visual() got an unexpected keyword argument 'color'

### ISSUE THREAD

**Issue by LittlePotatoChip** [haosulab/SAPIEN#190]
**System:**
 - OS version: Ubuntu 24.04
 - Python version : Python 3.11.11
 - SAPIEN version (pip freeze | grep sapien): 3.0.0b1
 - Environment: python

**Describe the bug**
can't run the demo hello_world.py 
`(maniskill) potato@potato-MS-7E13:~/workplace/SAPIEN$ python python/py_package/example/hello_world.py 
/home/potato/workplace/SAPIEN/python/py_package/example/hello_world.py:18: DeprecationWarning: Engine is deprecated. use sapien.Scene() directly.
  engine = sapien.Engine()  # Create a physical simulation engine
/home/potato/workplace/SAPIEN/python/py_package/example/hello_world.py:19: DeprecationWarning: SapienRenderer is no no longer needed.
  renderer = sapien.SapienRenderer()  # Create a renderer
Traceback (most recent call last):
  File "/home/potato/workplace/SAPIEN/python/py_package/example/hello_world.py", line 56, in <module>
    main()
  File "/home/potato/workplace/SAPIEN/python/py_package/example/hello_world.py", line 29, in main
    actor_builder.add_box_visual(half_size=[0.5, 0.5, 0.5], color=[1., 1., 1.])
TypeError: ActorBuilder.add_box_visual() got an unexpected keyword argument 'color'
`

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  conda activate maniskill
2. python hello_world.py 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/059ffd1d-4dce-41f3-a570-269013ac2a11)

**Additional context**
if I change that using:
actor_builder.add_box_visual(half_size=[0.5, 0.5, 0.5])
it can run
![image](https://github.com/user-attachments/assets/b301f24a-9da2-4def-8ef9-a2b9a78797ac)

**Comment by fbxiang** [comment]
It seems that your SAPIEN version is 3 but the repo where you are running the example is from SAPIEN 2. Also the documentation screenshot appears to also be SAPIEN 2? Could you verify this? In SAPIEN 3, there is only the material parameter and no color (since color and material are mutually exclusive).

**Comment by LittlePotatoChip** [comment]
> It seems that your SAPIEN version is 3 but the repo where you are running the example is from SAPIEN 2. Also the documentation screenshot appears to also be SAPIEN 2? Could you verify this? In SAPIEN 3, there is only the material parameter and no color (since color and material are mutually exclusive).

Thanks for repling.Yes,my SAPIEN version is 3. I want to know how can I find the documents of sapien 3 or how can I install sapien 2?

**Comment by fbxiang** [comment]
The documentation for SAPIEN3 is available at https://sapien-sim.github.io/docs/

I do not recommend using SAPIEN2 for new projects, but all legacy versions of SAPIEN are still available on pypi and can be installed with pip.

**Comment by LittlePotatoChip** [comment]
> The documentation for SAPIEN3 is available at https://sapien-sim.github.io/docs/
> 
> I do not recommend using SAPIEN2 for new projects, but all legacy versions of SAPIEN are still available on pypi and can be installed with pip.

thanks,it's done
